# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8eb2a0283ef76e2350e310867fa060d676e6066aff2e2e592cc004e2bd9b3b5a47d88b939b41d3b9207f28e93c576565a7dc5d8e611e522c7c512794615ca218

test:
  secret_key_base: c1e5c8bd844ba27af33be8d5a0eb9ef5681a90c52001d3c1d2b62c5daaaaf9b2d493316ea96092c14a5e9958047809b9825c340c71dc9a7b61598c8151dfa55a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
